name: "Integration Tests"
on:
  push:
    branches:
      - master
      - for-master
jobs:
  integration:
    strategy:
      matrix:
        name: [
          "altlinux",
          "fedora",
          "ubuntu",
        ]
        test: [
          "btrfs-subvol",
          "luks",
          "luks+crypttab+noparam",
          "luks+lukskey-noparam",
          "luks+lukskey-plain",
          "luks+lukskey-raw",
          "luks-over-lvm",
          "luks-over-raid1",
          "lvm",
          "lvm+luks",
          "partition",
          "partition+usr",
          "pipeline",
          "raid1",
          "raid1+raid5",
          "raid1-degraded",
          "raid5",
        ]
      fail-fast: false
      #max-parallel: 6
    runs-on: ubuntu-latest
    name: "${{ matrix.name }}, root:${{ matrix.test }}"
    steps:
      - name: "Prepare KVM"
        run: |
          test -c /dev/kvm && sudo chmod -v 666 /dev/kvm ||:

      - name: "Install packages"
        run: |
          sudo apt-get -qq -y update
          sudo apt-get -qq -y install git expect qemu-kvm

      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Checkout submodules"
        run: |
          git submodule set-url external/busybox/upstream https://github.com/mirror/busybox
          git submodule update --init --recursive

      - name: "Test"
        env:
          TIMEOUT: 30m
        run: |
          testing/testing-${{ matrix.name }} test-root-${{ matrix.test }}

  efi:
    strategy:
      matrix:
        name: [
          "altlinux",
        ]
        test: [
          "efi-partition",
          "efi-reqpartition",
        ]
      fail-fast: false
    runs-on: ubuntu-latest
    name: "${{ matrix.name }}, root:${{ matrix.test }}"
    steps:
      - name: "Prepare KVM"
        run: |
          test -c /dev/kvm && sudo chmod -v 666 /dev/kvm ||:

      - name: "Install packages"
        run: |
          sudo apt-get -qq -y update
          sudo apt-get -qq -y install git qemu-kvm ovmf

      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Checkout submodules"
        run: |
          git submodule set-url external/busybox/upstream https://github.com/mirror/busybox
          git submodule update --init --recursive

      - name: "Test"
        env:
          TIMEOUT: 30m
        run: |
          testing/testing-${{ matrix.name }}-efi test-root-${{ matrix.test }}

  zfs:
    strategy:
      matrix:
        name: [
          "ubuntu",
        ]
        test: [
          "zfs-partition",
        ]
      fail-fast: false
    runs-on: ubuntu-latest
    name: "${{ matrix.name }}, root:${{ matrix.test }}"
    steps:
      - name: "Prepare KVM"
        run: |
          test -c /dev/kvm && sudo chmod -v 666 /dev/kvm ||:

      - name: "Install packages"
        run: |
          sudo apt-get -qq -y update
          sudo apt-get -qq -y install git qemu-kvm ovmf

      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Checkout submodules"
        run: |
          git submodule set-url external/busybox/upstream https://github.com/mirror/busybox
          git submodule update --init --recursive

      - name: "Test"
        env:
          TIMEOUT: 30m
        run: |
          testing/testing-${{ matrix.name }} test-root-${{ matrix.test }}

  network:
    strategy:
      matrix:
        name: [
          "altlinux",
        ]
        test: [
          "sshfsroot",
        ]
        nettype: [
          "dhcp",
          "static1",
        ]
      fail-fast: false
    runs-on: ubuntu-latest
    name: "${{ matrix.name }}, root:${{ matrix.test }}, net:${{ matrix.nettype }}"
    steps:
      - name: "Prepare KVM"
        run: |
          test -c /dev/kvm && sudo chmod -v 666 /dev/kvm ||:

      - name: "Install packages"
        run: |
          sudo apt-get -qq -y update
          sudo apt-get -qq -y install git qemu-kvm

      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Checkout submodules"
        run: |
          git submodule set-url external/busybox/upstream https://github.com/mirror/busybox
          git submodule update --init --recursive

      - name: "Test"
        env:
          TIMEOUT: 5m
        run: |
          testing/testing-${{ matrix.name }}-${{ matrix.test }} ${{ matrix.nettype }}
